### ISSUE TITLE
Timelapse redesign v2

### ISSUE THREAD

**Issue by affan00** [evercam/Timelapse#22]
- [x] Remove “Create Account” from not logged in page
- [x] Put save button, under “Add File” … in green ?
- [x] Put delete button, in red, on same height as save, but aligned to right.

**Comment by liutingdu** [comment]
@affan00 I am trying to test it on mobile, just wondering, is it finished but not deployed yet?

**Comment by affan00** [comment]
@liutingdu Yes, it's complete but still not deployed. Soon Mr. Azhar will deploy it.

**Comment by affan00** [comment]
done
