### ISSUE TITLE
Improve mobile experience

### ISSUE THREAD

**Issue by liutingdu** [evercam/Timelapse#23]
I tried it on both Android and iOS, looks nice after the recent improvements 👍 

Small issues with the timelapse detail section (see screenshot):
- [x] The divider and video view is aligning right - should be centralized (Same issue for other tabs like 'settings')
- [x] The tab menus - it seems to me that 'options' should belong to 'Settings'? By reducing the menu items or use single word as tab title could help improve the crowded titles
- [x] Refresh button shouldn't be scaled in 'stats'

<image src="https://cloud.githubusercontent.com/assets/5046761/14715833/4cb28d4c-07e2-11e6-9434-f780b2dcf8de.jpg" width="350px">
<image src="https://cloud.githubusercontent.com/assets/5046761/14716353/8ad795de-07e4-11e6-824e-3ae3f50fb5e2.jpg" width="350px">

**Comment by affan00** [comment]
done
