### ISSUE TITLE
Sign out button is not working on laptop browser

### ISSUE THREAD

**Issue by liutingdu** [evercam/Timelapse#24]
Tested in Chrome, when I click 'Sign Out', nothing happens. 

But if I drag to reduce the browser width, the sign out button then replaced with a sign out icon, then it works by clicking the icon

**Comment by affan00** [comment]
@liutingdu I already fixed this issue with re-design v2 task and as soon as we deploy the changes related to re-design v2 it will work fine. So I am closing this issue.
