### ISSUE TITLE
Bugs found by Joe 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/Timelapse#30]
- [ ] Looping randomly. Seems to be related to multi-bitrate
- [x] Update Video.JS and then show Affan how you did it (he has a similar task in Dash)
- [x] Optimise the ffmpeg command to not lose so much resolution.
- [ ] Re-run ffmpeg on all timelapses.

Thanks Joe Dolan :)

**Comment by azharmalik3** [comment]
@marcoherbst I am not able to replicate looping issue after update videojs.

Removed `-profile` parameter from FFmpeg command and used `-preset: slow` and `-tune: stillimage` to create good quality HLS stream. It creates good quality medium and high stream but low stream loose video quality. Also, loose quality for those cameras who have different resolution images (like Bennett doorset VH). Also, try to decrease `Constant Rate Factor CRF` value to create a lossless video which is much better but create a large file in Gbs.

Also Posted a question on [stackoverflow](http://stackoverflow.com/questions/39271569/how-to-create-video-from-different-resolution-images) about this issue.

**Comment by azharmalik3** [comment]
Experiment with different FFmpeg parameters to improve the quality of the stream. Removed `level` and `-g` parameter because these parameters were used with `profile` parameter. Used `b:v` parameter to control the bandwidth and `maxrate` which is used for video maximum bitrate.

**Comment by azharmalik3** [comment]
Old parameters: 
```
ffmpeg -threads 1 -y -framerate 24 -i images/%d.jpg -c:v libx264 -pix_fmt yuv420p -profile:v baseline -level 2.1 -maxrate 500K -bufsize 2M -crf 18 -r 24 -g 30  -f hls -hls_time 2 -hls_list_size 0 -s 480x270 ts/low.m3u8
```

New parameters:
```
ffmpeg -threads 1 -y -framerate 24 -i images/%d.jpg -c:v libx264 -pix_fmt yuv420p -preset slow -tune stillimage -b:v 64K -maxrate 10000k -bufsize 64k -crf 28 -r 24 -f hls -hls_time 2 -hls_list_size 0 ts/low.m3u8
```

I new command, if we use video bitrate `-b:v` only then FFmpeg auto choose output maximum rate which creates a larger output file. So, I use `maxrate` to keep good video quality and reasonable file size.

I tried `-b:v` from 64K to 500K to create HLS and choose 64K because it creates a good quality of video with affordable file size (1 to 2 MB) and more than 64k bitrate creates 11 to 15 MB file.

**Comment by azharmalik3** [comment]
I think it's done.
