### ISSUE TITLE
An Admin Area

### ISSUE THREAD

**Issue by marcoherbst** [evercam/Timelapse#9]
(Maybe in our current admin area? ... since the long term destiny of Timelapse is almost certainly tighter integration with Evercam)

**Comment by marcoherbst** [comment]
@ijunaidfarooq this task will be for you. My preference is to do it in admin.evercam. , but you can choose, if it's much easier it can be in timelapse.evercam.io .... Main report is just a list of all timelapses and their size and status. with a click to login to that account.

**Comment by ijunaidfarooq** [comment]
@marcoherbst We will do that in Admin Area.. alongside with all other reports.. :)

**Comment by azharmalik3** [comment]
Already completed.
